### ISSUE TITLE
Get background working for ‘sitewide’ components

### ISSUE THREAD

**Issue by adamglenn** [wvuweb/wvu-design-system-v2#44]
Right now, you can assign a background image to a component by labeling an image with the format `{page-slug}-{component-name}-background` e.g. `home-hero-1-background`. But for components that are set to `scope: site` that you want to have the same background, you still have to add labels for each of these components individually. I’d like for the user to be able to add a label that includes `site-` plus the component name and instance number e.g. `site-hero-1-background` or `site-hero-5-background`, which will apply to all `scope: site` components in a site that are the same i.e. use the same component name and instance number. Since the code that assigns the background images is built into CleanSlate, I’m asking Nathan to do this.

**Comment by nreckart** [comment]
While looking at this, I noticed a lot of manual scope checking within the components to append 'site-' to the basename for site scoped components, when defining the component. 

```
  assign scope = scope | default: slot.scope
  if scope == 'site'
    assign basename = "site-hero"
  else
    assign basename = "hero"
  endif
```

Since nearly every component contains such logic, it would seem that this is a process that should be automatically handled within the component logic of CleanSlate. I made the necessary changes to make this happen. If a component's scope is set to 'site', or a value that can be considered as a boolean true, such as 1, true, t, yes, or y, then 'site-' will be prepended to the basename of the compenent, which in-turn is used to build region names, etc. I also made the changes necessary to also apply this for the background images, which are done with the `component.bgStyler` component helper method.

These changes have been deployed to staging.

I also created a new ds2 branch, pr/sitewide-backgrounds, and removed all of the manual scope logic from every component (I think). I've done some testing in staging and things seem to work as expected and I don't think I broke anything, but I'd like others to test within staging to ensure that I didn't inadvertently break existing functionality. The changes to CleanSlate would affect ALL sites/themes that currently use Liquid.

**Comment by adamglenn** [comment]
It seems to work correctly. If this applies to all Liquid sites, however, I wonder if it could cause a problem with the original Design System Liquid sites. For those components, we didn't prepend the 'site-' to the basename. We added that as a new feature in Design System 2 so conflicts wouldn't arise if someone set a component to 'sitewide', then later decided to use the same component with the same instance number elsewhere in their site, but with scope: page instead. What would happen is that once you set a component to 'sitewide', all of the other components with the same name and instance number would get 'stuck' like that, and the user could no longer use that component/instance number combo if they wanted to use it as scope: page elsewhere. I only know of this happening once (Bobby Dillon did it on accident with WVU Online), but others may have used this feature intentionally, in which case wouldn’t this new fix change the region names of those components and cause them to lose their content? I couldn’t test it because when I tried to create a site using the Design System Liquid Theme in staging and set one of the components to ‘Sitewide’ in the Super Template, the region name had ‘site-‘ at the beginning as if it were using your new code.

One other thing, I noticed that in some of the components, you deleted my defaultComponentClasses and defaultHeaderClasses variables (for example in the Featurettes component). Was that intentional?

**Comment by nreckart** [comment]
Yes, it sounds like these changes would indeed break existing DS1 themes. That's something I hadn't considered. I will need to come up with a way to check which version of the design system a particular theme is using or is based on. One possibility is to just check if the theme "imports" the wvu-design-system-v2 theme/git repo, but this may only work for custom themes. For sites that use the wvu-design-system-v2 theme directly, some other method will probably be needed.

I deleted duplicate variable assignments from two components:
* _wvu-action-hero.html
* _wvu-featurettes.html 

In both cases, the variable assignments deleted were exact duplicates of assignments that were done just a few lines above. Please triple check me on that, but I'm fairly certain they were exact duplicates and unnecessary.

**Comment by nreckart** [comment]
I just deployed some changes to staging that should limit the automatic 'site-' application to only themes that are using Design System V2. The original functionality should remain for existing themes using DS1. 

A theme is considered DS2 if it is the actual DS2 theme/repo or imports it via it's config.yml. The "repo" is hardcoded to `git@github.com:wvuweb/wvu-design-system-v2.git`, so if the official DS2 repo ever changes, the CleanSlate config will need updated accordingly.

@adamglenn could you test the `pr/sitewide-backgrounds` branch again, when you get a chance?
