### ISSUE TITLE
Not able to reorder items in a page collection using "Loop By" selection

### ISSUE THREAD

**Issue by rebecca-patton** [wvuweb/wvu-design-system-v2#71]
## Steps to reproduce the issue

  1. Create and publish several articles in a blog index.
  1. Label the articles for inclusion in a Page Collection component.
  1. Try to move one article within the Page Collection by editing the publish date or updating the page.

## Results

I am unable to move the article "The Last Word: The International Mountaineer" in [this page collection](https://wvumagazine-v2.sandbox.wvu.edu/archive/summer-2023) to the end of the list. The order on that page does not reflect the [sort order](https://cleanslate.wvu.edu/sites/1605/pages) in CleanSlate.

## What doesn't work

  1. Unpublishing and re-publishing the page.
  1. Updating content on the page and publishing. 
  1. Changing the Published on date/time in properties.
  2. I made a [test](https://wvumagazine-v2.sandbox.wvu.edu/article-heros/test-page-collection) using normal backpages and it also doesn't seem affected by publish date. 

## What does work

Sorting by alternative name does seem to work but unfortunately I don't want to change the name of the articles.

## More Questions

  1. What do Published At, Updated At, Content Updated At actually mean? 

Thanks!

**Comment by adamglenn** [comment]
@rebecca-patton I *believe* I have this working correctly now. Can you test your Magazine site for me to make sure? What you want to do is use the "Published At" loop by option for your page collection component. I think what was happening is that the sort function in the page collection components wasn't working, at least not with blog articles, and by default the articles were being sorted based on when they were created rather than published.

**Comment by rebecca-patton** [comment]
Yes, using the "published at" option is now working. It's sorting by the date and time in page/article properties, which should work well for this case. Thank you!
